"use strict";
exports.__esModule = true;
var pregunta_1 = require("./pregunta");
var examen_1 = require("./examen");
var alumno_1 = require("./alumno");
var rendicionExamen_1 = require("./rendicionExamen");
var matPreg1 = ['A', 'B', 'C', 'D'];
var matPreg2 = ['A', 'B', 'C', 'D'];
var matPreg3 = ['A', 'B', 'C', 'D'];
var pregunta1 = new pregunta_1.Pregunta('Cual es la raiz cubica de 27?', matPreg1, 1, 2);
var pregunta2 = new pregunta_1.Pregunta('Cual es la raiz cuadrada de 81?', matPreg2, 3, 2);
var pregunta3 = new pregunta_1.Pregunta('Cuanto es 12 a la enesima potencia?', matPreg3, 2, 2);
var preguntasMatematica = [pregunta1, pregunta2, pregunta3];
var histPreg1 = ['A', 'B', 'C', 'D'];
var histPreg2 = ['A', 'B', 'C', 'D'];
var histPreg3 = ['A', 'B', 'C', 'D'];
var pregunta4 = new pregunta_1.Pregunta("En que pais se produce la revolucion industrial?", histPreg1, 2, 3);
var pregunta5 = new pregunta_1.Pregunta("En que año se produce la revolucion francesa?", histPreg2, 3, 3);
var pregunta6 = new pregunta_1.Pregunta("A que epoca se denomina el Medioevo?", histPreg3, 2, 4);
var preguntasHistoria = [pregunta4, pregunta5, pregunta6];
var examenMatematica = new examen_1.Examen(preguntasMatematica, "Matematica", 6);
var examenHistoria = new examen_1.Examen(preguntasHistoria, "Historia", 6);
var rtasHistoria = [];
var rtasMatematica = [];
var rendicionExamenMatematica = new rendicionExamen_1.RendicionDeExamen(examenMatematica, rtasMatematica);
var rendicionExamenHistoria = new rendicionExamen_1.RendicionDeExamen(examenHistoria, rtasHistoria);
var examenesRendidos = [rendicionExamenMatematica, rendicionExamenHistoria];
var estudiante = new alumno_1.Alumno(examenesRendidos, "Matias", 35577812);
var respuestasExamenHistoria = ["A", "A", "C"];
var respuestasExamenMatematica = ["B", "C", "B"];
estudiante.rendirExamen(examenHistoria, rtasHistoria);
estudiante.rendirExamen(examenMatematica, rtasMatematica);
rendicionExamenMatematica.estaAprobado();
rendicionExamenHistoria.estaAprobado();
